[gcloud]
format = '[$symbol $project(\($region\))]($style) '

[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "

[git_status]
up_to_date = "âœ“ "

[python]
symbol = " ğŸ "
